"""
Problem 45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal         Pn=n(3n1)/2         1, 5, 12, 22, 35, ...
Hexagonal         Hn=n(2n1)         1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
def traditional():
    T = 286
    P = 166
    H = 144
    limit = 100000
    triangular = set([x * (x + 1) / 2 for x in range(T, limit)])
    pentagonal = set([x * (3 * x - 1) / 2 for x in range(P, limit)])
    hexagonal = set([x * (2 * x - 1) for x in range(H, limit)])

    return triangular.intersection(pentagonal.intersection(hexagonal))

print "Answer:", traditional()
